name: Laravel Auto Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix permissions (important)
        run: sudo chown -R $USER:$USER .

      - name: Stop containers
        run: docker compose down || true

      - name: Build containers
        run: docker compose build --no-cache

      - name: Start containers
        run: docker compose up -d

      - name: Show status
        run: docker ps